/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import NapakalakiGame.BadConsequence;
import NapakalakiGame.SpecificBadConsequence;
import NapakalakiGame.NumericBadConsequence;
import NapakalakiGame.DeathBadConsequence;
import NapakalakiGame.TreasureKind;
/**
 *
 * @author alfonso
 */
public class BadConsequenceView extends javax.swing.JPanel {

    
    private BadConsequence badConsequenceModel;
    
    
    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
        
        textView.setLineWrap(true);
        visibleTreasures.setLineWrap(true);
        hiddenTreasures.setLineWrap(true);
        
        textView.setWrapStyleWord(true);
        visibleTreasures.setWrapStyleWord(true);
        hiddenTreasures.setWrapStyleWord(true);
    }

    
    public void setBadConsequence(BadConsequence bc)
    {
        badConsequenceModel = bc;
        textView.setText(bc.getText());
        levelsView.setText("Niveles: "+bc.getLevels());
        System.out.println(bc.getClass().getName());
        if (java.util.Objects.equals(bc.getClass().getName(),"NapakalakiGame.SpecificBadConsequence"))
        {   
            death.setVisible(false);
            visibleTreasuresLabel.setText("Tesoros visibles");
            
            // Se borra el texto que hubiera escrito antes
            visibleTreasures.setText(null);
            hiddenTreasures.setText(null);
                    
            for (TreasureKind treasure : ((SpecificBadConsequence)bc).getSpecificVisibleTreasures())
            {
                visibleTreasures.append(treasure.toString()+"\n");
            }
            
            hiddenTreasuresLabel.setText("Tesoros ocultos");
            
            for (TreasureKind treasure : ((SpecificBadConsequence)bc).getSpecificHiddenTreasures())
            {
                hiddenTreasures.append(treasure.toString()+"\n");
            }
        }
        else
        {
            if (!(java.util.Objects.equals(bc.getClass().getName(),"NapakalakiGame.DeathBadConsequence")))
            {
                death.setVisible(false);
                visibleTreasures.setText(Integer.toString(((NumericBadConsequence)bc).getNVisibleTreasures()));
                hiddenTreasures.setText(Integer.toString(((NumericBadConsequence)bc).getNHiddenTreasures()));   
            }
            else
            {
                death.setVisible(true);
                visibleTreasures.setText(Integer.toString(((DeathBadConsequence)bc).getNVisibleTreasures()));
                hiddenTreasures.setText(Integer.toString(((DeathBadConsequence)bc).getNHiddenTreasures()));
            }
            
            visibleTreasuresLabel.setText("Numero de tesoros visibles");
            hiddenTreasuresLabel.setText("Numero de tesoros ocultos");
            

        }
        
        repaint();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        levelsView = new javax.swing.JTextField();
        visibleTreasuresLabel = new javax.swing.JLabel();
        hiddenTreasuresLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        visibleTreasures = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        hiddenTreasures = new javax.swing.JTextArea();
        death = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textView = new javax.swing.JTextArea();

        levelsView.setEditable(false);
        levelsView.setText("Levels");

        visibleTreasuresLabel.setText("jLabel1");

        hiddenTreasuresLabel.setText("jLabel2");

        visibleTreasures.setEditable(false);
        visibleTreasures.setColumns(20);
        visibleTreasures.setRows(5);
        jScrollPane3.setViewportView(visibleTreasures);

        hiddenTreasures.setEditable(false);
        hiddenTreasures.setColumns(20);
        hiddenTreasures.setRows(5);
        jScrollPane4.setViewportView(hiddenTreasures);

        death.setText("Mal rollo mortal");

        textView.setColumns(20);
        textView.setRows(5);
        textView.setText("Text");
        jScrollPane1.setViewportView(textView);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(levelsView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visibleTreasuresLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hiddenTreasuresLabel)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(death)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visibleTreasuresLabel)
                    .addComponent(hiddenTreasuresLabel)
                    .addComponent(levelsView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(death))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel death;
    private javax.swing.JTextArea hiddenTreasures;
    private javax.swing.JLabel hiddenTreasuresLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField levelsView;
    private javax.swing.JTextArea textView;
    private javax.swing.JTextArea visibleTreasures;
    private javax.swing.JLabel visibleTreasuresLabel;
    // End of variables declaration//GEN-END:variables
}
