/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import NapakalakiGame.BadConsequence;
import NapakalakiGame.NumericBadConsequence;
import NapakalakiGame.SpecificBadConsequence;
import NapakalakiGame.DeathBadConsequence;
import NapakalakiGame.TreasureKind;

/**
 *
 * @author alfonso
 */
public class PendingBadConsequenceView extends javax.swing.JPanel {

    
    private BadConsequence pendingBadConsequenceModel;
    
    
    public void setPendingBadConsequence(BadConsequence pbc)
    {
        pendingBadConsequenceModel = pbc;
        
        visibleTreasures.setText(null);
        hiddenTreasures.setText(null); 
        
        if ((pbc == null) )
        {
            visibleTreasuresLabel.setText("Sin tesoros visibles pendientes");
            visibleTreasures.setText(null);
            hiddenTreasuresLabel.setText("Sin tesoros ocultos pendientes");
            hiddenTreasures.setText(null);    
        }
        
        
        if (pbc.getClass().getName().equals("NapakalakiGame.SpecificBadConsequence"))
        {
            visibleTreasuresLabel.setText("Tesoros visibles a descartar");
            
            for (TreasureKind treasure : ((SpecificBadConsequence)pbc).getSpecificVisibleTreasures())
            {
                visibleTreasures.append(treasure.toString()+"\n");
            }
            
            hiddenTreasuresLabel.setText("Tesoros ocultos a descartar");
            
            for (TreasureKind treasure : ((SpecificBadConsequence)pbc).getSpecificHiddenTreasures())
            {
                hiddenTreasures.append(treasure.toString()+"\n");
            }
        }
        
        else
        {    
            visibleTreasuresLabel.setText("Numero de tesoros visibles a descartar");
            hiddenTreasuresLabel.setText("Numero de tesoros ocultos a descartar");
            
            if (pbc.getClass().getName().equals("NapakalakiGame.NumericBadConsequence"))
            {
                visibleTreasures.setText(Integer.toString(((NumericBadConsequence)pbc).getNVisibleTreasures()));
                hiddenTreasures.setText(Integer.toString(((NumericBadConsequence)pbc).getNHiddenTreasures()));
            }
            else
            {
                visibleTreasures.setText(Integer.toString(((DeathBadConsequence)pbc).getNVisibleTreasures()));
                hiddenTreasures.setText(Integer.toString(((DeathBadConsequence)pbc).getNHiddenTreasures()));
                
            }
        }
        
        repaint();
    }
    
    
    /**
     * Creates new form PendingBadConsequenceView
     */
    public PendingBadConsequenceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        visibleTreasuresLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hiddenTreasures = new javax.swing.JTextArea();
        hiddenTreasuresLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        visibleTreasures = new javax.swing.JTextArea();

        visibleTreasuresLabel.setText("Sin tesoros visibles pendientes");

        hiddenTreasures.setEditable(false);
        hiddenTreasures.setColumns(20);
        hiddenTreasures.setRows(5);
        jScrollPane1.setViewportView(hiddenTreasures);

        hiddenTreasuresLabel.setText("Sin tesoros ocultos pendientes");

        visibleTreasures.setEditable(false);
        visibleTreasures.setColumns(20);
        visibleTreasures.setRows(5);
        jScrollPane2.setViewportView(visibleTreasures);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(visibleTreasuresLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(hiddenTreasuresLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hiddenTreasuresLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(visibleTreasuresLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea hiddenTreasures;
    private javax.swing.JLabel hiddenTreasuresLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea visibleTreasures;
    private javax.swing.JLabel visibleTreasuresLabel;
    // End of variables declaration//GEN-END:variables
}
