/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import NapakalakiGame.CombatResult;

/**
 *
 * @author alfonso
 */
public class ResultMessage extends javax.swing.JDialog {

    
    private CombatResult result;
    
    
    /**
     * Creates new form ResultMessage
     */
    public ResultMessage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                    System.exit(0);
            }
        });
        
                
       
    }
    
    
    public void setMessage(CombatResult combatResult, String playerName)
    {
        result  = combatResult;
        
        
        switch (combatResult)
        {
            case WIN:
            {
                resultLabel.setText(playerName + " gana el combate");
                break;
            }
            case LOSE:
            {
                resultLabel.setText(playerName + " pierde el combate, ahora debe cumplir el mal rollo");
                break;
            }
            case LOSEANDCONVERT:
            {
                resultLabel.setText(playerName + " pierde el combate y se convierte en un sectario, y también debe cumplir el mal rollo");
                break;
            }
            case WINGAME:
            {
                resultLabel.setText(playerName + " gana la partida. Enhorabuena!!!");
                break;
            }
            
            
        }
        
        this.pack();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resultado del combate");

        resultLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        resultLabel.setText("jLabel1");

        okButton.setText("OK");
        okButton.setName("OK"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okButton)
                    .addComponent(resultLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(resultLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(okButton)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        if (result == CombatResult.WINGAME)
            System.exit(0);
        else
            this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton okButton;
    private javax.swing.JLabel resultLabel;
    // End of variables declaration//GEN-END:variables
}
