/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import NapakalakiGame.Treasure;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
/**
 *
 * @author alfonso
 */
public class TreasureView extends javax.swing.JPanel {

    private Treasure treasureModel;
    private boolean selected = false;
    
    
    public void setTreasure (Treasure aTreasure)
    {
        
        treasureModel = aTreasure;
        this.nameView.setText (treasureModel.getName());
        this.bonusView.setText("Bonus: "+aTreasure.getBonus());
        this.treasureKindView.setText(aTreasure.getType().toString());
        
        this.setBackground(Color.GREEN);
        setOpaque(false);
        
        repaint();
    }
    
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
    }
    
    
    public boolean isSelected()
    {
        return selected;
    }
    
    
    public Treasure getTreasure()
    {
        return treasureModel;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameView = new javax.swing.JLabel();
        bonusView = new javax.swing.JTextField();
        treasureKindView = new javax.swing.JTextField();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        nameView.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nameView.setText("Name");

        bonusView.setEditable(false);

        treasureKindView.setEditable(false);
        treasureKindView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treasureKindViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bonusView, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameView)
                    .addComponent(treasureKindView, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameView)
                .addGap(18, 18, 18)
                .addComponent(bonusView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(treasureKindView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void treasureKindViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treasureKindViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_treasureKindViewActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        if (selected)
        {
            selected = false;
            //this.setBackground(Color.GREEN);
            setOpaque(false);
        }   
        else
        {
            selected = true;
            setOpaque(true);
        }
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bonusView;
    private javax.swing.JLabel nameView;
    private javax.swing.JTextField treasureKindView;
    // End of variables declaration//GEN-END:variables
}
